version: 2
jobs:
  deploy:
    working_directory: /app
    docker:
      - image: python:alpine
    steps:
      - checkout
      - run:
          name: Install S4Cmd
          command: |
            pip install s4cmd
      - run:
          name: Clean up files we don't need
          command: |
            rm -rf .git .circleci
      - deploy:
          name: Deploy to S3
          command: |
            s4cmd --API-ACL=public-read sync ./ s3://$S3_BUCKET/
workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
